### ISSUE TITLE
stuck in pyscreenshot.grab()

### ISSUE THREAD

**Issue by Mehsan79** [FirePlank/Auto-Chess#1]
hey there
perfect code
but I stuck in line 90-97 and the program didn't run I think it cannot recognize the chessboard
however I opened lichess page on the half right of my screen and the other is the code
could you please help me
thanks in advance
![Screenshot (15)](https://user-images.githubusercontent.com/67195882/128394438-ef4ce731-7284-48cf-b061-5c4c6fa16af2.png)

**Comment by FirePlank** [comment]
Hey! Does it give any errors or anything and also did you download all the required packages?

**Comment by Mehsan79** [comment]
yep, I think so
I have installed all text libraries successfully
it just hang on without any result then my system get runtime error or sth like this after an hour
any idea?

**Comment by FirePlank** [comment]
Try one of the options in the troubleshooting section, if all else fails try using tensorflow 2.5.0
