### ISSUE TITLE
stuck when i try to start the script 

### ISSUE THREAD

**Issue by foxsambuca** [FirePlank/Auto-Chess#12]
after  pip install -r requirements.txt and python Auto-Chess.py  says this 

![Immagine 2023-01-20 034100](https://user-images.githubusercontent.com/114025921/213606523-25c0fefb-a16b-471e-83c2-edcb46fefb8e.png)
 The last sentence is Italian and means impossible to find the specified file

**Comment by FirePlank** [comment]
This project has been dormant for a few years already and will most likely not work for you when running. I'm sure there are more recent projects that achieve the same functionality that this project does and I encurage you to seek them out.
