### ISSUE TITLE
After choosing the color nothing happens

### ISSUE THREAD

**Issue by MihCWats** [FirePlank/Auto-Chess#13]
After choosing the color nothing else happens from the script, it doesn't try to move or calculate moves or anything, as seen in the screenshot. I was on lichess.org and have default settings

![image](https://user-images.githubusercontent.com/58134026/214756912-ffb01d07-6b13-4de1-b671-73319ef91631.png)

**Comment by FirePlank** [comment]
This project has been dormant for a few years already and will most likely not work for you when running. I'm sure there are more recent projects that achieve the same functionality that this project does and I encurage you to seek them out.
