### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by snapoli10** [FirePlank/Auto-Chess#2]
Hello,
My script gets stuck. Nothing else appears after that.
The only error I found was when installing Pillow, so I edited the Pillow version in the requirements.txt to the latest to make it work. It's the only way I found. Could it be this?

**Comment by FirePlank** [comment]
Maybe try installing the latest version of Pillow instead of the one that is within the versions set in requirements.txt
meaning install the latest version of Pillow sepperately instead of doing pip install -r requirements.txt
