### ISSUE TITLE
help

### ISSUE THREAD

**Issue by realpritam** [FirePlank/Auto-Chess#5]

**Comment by realpritam** [comment]
![image](https://user-images.githubusercontent.com/105146731/186462530-49a596c9-aa05-4125-b199-343545e50a7e.png)

**Comment by FirePlank** [comment]
Did you do `pip install -r requirements.txt" before running the script.

**Comment by realpritam** [comment]
![image](https://user-images.githubusercontent.com/105146731/186503387-6c54a1ac-5d9e-4b71-821b-bb37027a1228.png)
i did

**Comment by FirePlank** [comment]
Maybe try installing the latest version of Pillow instead of the one that is within the versions set in requirements.txt
meaning install the latest version of Pillow sepperately instead of doing `pip install -r requirements.txt`
