### ISSUE TITLE
Error while trying to install package (Pillow)

### ISSUE THREAD

**Issue by BambangLife** [FirePlank/Auto-Chess#7]
when i try to run Auto-Chess.py it just say:
C:\Users\user\Downloads\Chess1\Auto-Chess-main>python Auto-Chess.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Chess1\Auto-Chess-main\Auto-Chess.py", line 1, in <module>
    import chess.engine
ModuleNotFoundError: No module named 'chess'

**Comment by BambangLife** [comment]
![image](https://user-images.githubusercontent.com/112305145/210210090-dc59c0ea-5970-4759-9e4a-7b06460f0012.png)

**Comment by BambangLife** [comment]
![image](https://user-images.githubusercontent.com/112305145/210210113-05c231b9-7d0c-4665-a919-2d3205bd6545.png)

**Comment by FirePlank** [comment]
What python version are you using, Pillow might still be in beta for python 3.11 etc. since its currently trying to instlal it from source it seems, if all else fails you could try reverting to an older python version such as 3.9 or 3.8

**Comment by BambangLife** [comment]
how i do set the new latest version of Pillow?

**Comment by BambangLife** [comment]
![image](https://user-images.githubusercontent.com/112305145/210309033-47a06484-7ebb-4ba7-8077-0cd1490a6939.png)

**Comment by BambangLife** [comment]
then what do i do with this ?
![image](https://user-images.githubusercontent.com/112305145/210311228-7c2d6dd1-8ca6-416f-8002-98997a0c6908.png)

**Comment by FirePlank** [comment]
now you have to install the other dependencies aside from Pillow that are in requirements.txt since none of the packages install once even one fail when trying to install requirements.txt packages

**Comment by BambangLife** [comment]
> now you have to install the other dependencies aside from Pillow that are in requirements.txt since none of the packages install once even one fail when trying to install requirements.txt packages

ok

**Comment by BambangLife** [comment]
> now you have to install the other dependencies aside from Pillow that are in requirements.txt since none of the packages install once even one fail when trying to install requirements.txt packages

does request too?

**Comment by FirePlank** [comment]
if it failed, let me know if the issue has been resolved
