### ISSUE TITLE
stuck 

### ISSUE THREAD

**Issue by FunnyCakes** [FirePlank/Auto-Chess#8]
File "Auto-Chess.py", line 105
    print(f"Unable to detect a valid board position... Detected board position with {round(accuracy, 2)}% confidence was:")
                                                                                                                         ^
SyntaxError: invalid syntax

what does this mean

**Comment by FirePlank** [comment]
This error message is indicating that there is a syntax error on line 105 of your "Auto-Chess.py" file. The specific issue is with the use of the print(f"...") syntax.
This is a feature introduced in python 3.6 called "formatted string literals" or "f-strings" which allows you to embed expressions inside string literals, using {}.
It seems that the version of python you are using is lower than 3.6.
