### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 0x00-sys** [FirePlank/Auto-Chess#9]
```
C:\Users\0x00\Downloads\Auto-Chess-main>python Auto-Chess.py
Traceback (most recent call last):
  File "C:\Users\0x00\Downloads\Auto-Chess-main\Auto-Chess.py", line 9, in <module>
    from chesstenso import tensorflow_chessbot
  File "C:\Users\0x00\Downloads\Auto-Chess-main\chesstenso\tensorflow_chessbot.py", line 43, in <module>
    import tensorflow as tf
  File "C:\Users\0x00\AppData\Roaming\Python\Python39\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\0x00\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\0x00\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\0x00\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                         ^
SyntaxError: invalid syntax
```

I don't understand what I did wrong, requirements failed but then I installed them all one by one, python version is 3.9.0

**Comment by FirePlank** [comment]
It seems like the python version you are using is 3.9.0, which should be compatible with TensorFlow.
The error message you provided suggests that there is an issue with the tensorflow package, specifically the file "tensorflow\python\pywrap_tensorflow_internal.py" .
It could be that the package was installed incorrectly or is an older version that is not compatible with your version of Python.
I would recommend trying to uninstall and reinstall the tensorflow package by running the command "pip uninstall tensorflow" and then "pip install tensorflow" in your command prompt.
You may also want to try installing the package in a virtual environment, in case there are any conflicting dependencies.
If the problem persist, you may want to look for more recent version or try to update or reinstall your tensorflow package.

**Comment by 0x00-sys** [comment]
```
C:\Users\0x00\Downloads\Auto-Chess-main>pip install tensorflow
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

Yeah, it seems like there is indeed some issue during tensorflow installation.

**Comment by FirePlank** [comment]
Great! let me know if you have any more issues. Try using tensorflow 2.5.0 if the most recent one's don't work.
